/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromosIndexRouteImport } from './routes/promos/index'
import { Route as DiscountIndexRouteImport } from './routes/discount/index'
import { Route as CategoryIndexRouteImport } from './routes/category/index'
import { Route as CategorySplatRouteImport } from './routes/category/$'
import { Route as CategoryBrendyIndexRouteImport } from './routes/category/brendy/index'
import { Route as CategoryBrendySplatRouteImport } from './routes/category/brendy/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromosIndexRoute = PromosIndexRouteImport.update({
  id: '/promos/',
  path: '/promos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountIndexRoute = DiscountIndexRouteImport.update({
  id: '/discount/',
  path: '/discount/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySplatRoute = CategorySplatRouteImport.update({
  id: '/category/$',
  path: '/category/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryBrendyIndexRoute = CategoryBrendyIndexRouteImport.update({
  id: '/category/brendy/',
  path: '/category/brendy/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryBrendySplatRoute = CategoryBrendySplatRouteImport.update({
  id: '/category/brendy/$',
  path: '/category/brendy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category/$': typeof CategorySplatRoute
  '/category': typeof CategoryIndexRoute
  '/discount': typeof DiscountIndexRoute
  '/promos': typeof PromosIndexRoute
  '/category/brendy/$': typeof CategoryBrendySplatRoute
  '/category/brendy': typeof CategoryBrendyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category/$': typeof CategorySplatRoute
  '/category': typeof CategoryIndexRoute
  '/discount': typeof DiscountIndexRoute
  '/promos': typeof PromosIndexRoute
  '/category/brendy/$': typeof CategoryBrendySplatRoute
  '/category/brendy': typeof CategoryBrendyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category/$': typeof CategorySplatRoute
  '/category/': typeof CategoryIndexRoute
  '/discount/': typeof DiscountIndexRoute
  '/promos/': typeof PromosIndexRoute
  '/category/brendy/$': typeof CategoryBrendySplatRoute
  '/category/brendy/': typeof CategoryBrendyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category/$'
    | '/category'
    | '/discount'
    | '/promos'
    | '/category/brendy/$'
    | '/category/brendy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category/$'
    | '/category'
    | '/discount'
    | '/promos'
    | '/category/brendy/$'
    | '/category/brendy'
  id:
    | '__root__'
    | '/'
    | '/category/$'
    | '/category/'
    | '/discount/'
    | '/promos/'
    | '/category/brendy/$'
    | '/category/brendy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategorySplatRoute: typeof CategorySplatRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  DiscountIndexRoute: typeof DiscountIndexRoute
  PromosIndexRoute: typeof PromosIndexRoute
  CategoryBrendySplatRoute: typeof CategoryBrendySplatRoute
  CategoryBrendyIndexRoute: typeof CategoryBrendyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promos/': {
      id: '/promos/'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof PromosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount/': {
      id: '/discount/'
      path: '/discount'
      fullPath: '/discount'
      preLoaderRoute: typeof DiscountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$': {
      id: '/category/$'
      path: '/category/$'
      fullPath: '/category/$'
      preLoaderRoute: typeof CategorySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/brendy/': {
      id: '/category/brendy/'
      path: '/category/brendy'
      fullPath: '/category/brendy'
      preLoaderRoute: typeof CategoryBrendyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/brendy/$': {
      id: '/category/brendy/$'
      path: '/category/brendy/$'
      fullPath: '/category/brendy/$'
      preLoaderRoute: typeof CategoryBrendySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategorySplatRoute: CategorySplatRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  DiscountIndexRoute: DiscountIndexRoute,
  PromosIndexRoute: PromosIndexRoute,
  CategoryBrendySplatRoute: CategoryBrendySplatRoute,
  CategoryBrendyIndexRoute: CategoryBrendyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
